export default {
  en: {
    tagline: "Making the web faster and more user-friendly",
    backToHome: "Home page",
    previous: "Previous",
    next: "Next",
    topLevelNav: "Top level navigation menu",
    endOfPage: "You've reached the end of the page.",
    toTheTop: "To the top",
    readMore: "Read more",
    morePostsStart: "",
    morePostsEnd: " more post(s) can be found in the archive.",
    tagged: "Tagged",
    seeAllTags: "See all tags",
    archive: "the archive",
    tags: "Tags",
  },
  it: {
    tagline: "Rendo il web più veloce e più facile da usare",
    backToHome: "Pagina iniziale",
    previous: "Precedente",
    next: "Successivo",
    topLevelNav: "Menu di navigazione principale",
    endOfPage: "Sei arrivato alla fine della pagina.",
    toTheTop: "Torna su",
    readMore: "Leggi tutto",
    morePostsStart: "Puoi trovare altri ",
    morePostsEnd: " articoli nell'archivio.",
    tagged: "Articoli con tag",
    seeAllTags: "Vedi tutti i tag",
    archive: "l'archivio",
    tags: "Tag",
  },
};
